import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: '--font-montserrat', // should match the font you're actually importing
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${montserrat.className}`}
      >
        {children}
      </body>
    </html>
  );
}
